# Generated by Django 3.2.12 on 2022-07-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'materia',
                'verbose_name_plural': 'materias',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.IntegerField()),
                ('f_nac', models.DateField(blank=True, help_text='aqui debe ingresar la fecha de nacimiento', null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('legajo', models.IntegerField()),
                ('tel', models.CharField(max_length=200)),
                ('curso', models.CharField(max_length=200)),
                ('Materia', models.ManyToManyField(to='WebCole.Materia', verbose_name='Materias')),
            ],
            options={
                'verbose_name': 'alumno',
                'verbose_name_plural': 'alumnos',
            },
        ),
    ]
